CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_BME280=y
CONFIG_VEML7700=y
CONFIG_LOG=y

# Enable for verbose output
# CONFIG_I2C_LOG_LEVEL_DBG=y

# CONFIG_SHELL=y

# Required for i2c scan
# CONFIG_I2C_SHELL=y

# Required for sensor get
# CONFIG_SENSOR_SHELL=y